PPO_HYPERPARAMS: {
    gamma: 0.9,
    lr: 0.001,
    lr_schedule: [ [ 0, 0.0003 ], [ 10000, 0.0001 ] ],
    use_critic: True,
    use_gae: True,
    kl_coeff: 0.2,
    sgd_minibatch_size: 128,
    num_sgd_iter: 10,
    shuffle_sequences: True,
    vf_loss_coeff: 0.5,
    entropy_coeff: 0.01,
    clip_param: 0.2,
    vf_clip_param: 10.0,
    grad_clip: 0.5,
    kl_target: 0.01
}

